#
# This is free software, lisence use MIT.
# 

name: Update-dockerfile

on:
  push:
    paths:
      - '.github/workflows/main.yml'
  watch:
    types: started
  repository_dispatch:
  workflow_dispatch:

jobs:
  dockerfile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
    
    - name: Set git identity
      run : |
        docker build -t csjtl/openwrt-compiler-env-for-docker:v1.01 .
        docker save -o ./openwrt-compiler-env-for-docker:v1.01.tar csjtl/openwrt-compiler-env-for-docker:v1.01
    
    - name: Upload firmware for artifact
      uses: actions/upload-artifact@main
      continue-on-error: true
      with:
        path: |
          openwrt-compiler-env-for-docker:v1.01.tar
    
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: csjtl/openwrt-compiler-env-for-docker:v1.01
  
    - name: Apply
      run: |
        git add .
        git commit -m "$(date +%Y-%m-%d" "%H:%M:%S)" || true
        git push
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
